import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { BASE_DIR, TASK_PORT_BASE, TASK_PORT_BLOCK_SIZE, TASK_PORT_SLOT_COUNT } from "./constants.ts";
import { dotenvValue, parseSimpleDotenv } from "./dotenv.ts";
import { fail } from "./errors.ts";
import { run } from "./process.ts";

export type TaskPorts = {
  slot: number;
  apiPort: number;
  dashPort: number;
  sitePort: number;
  adminPort: number;
  storybookPort: number;
  ciApiPort: number;
  ciDashPort: number;
  accountPort: number;
};

function numberFromEnv(values: Record<string, string>, key: string): number | null {
  const value = values[key];
  if (!value || !/^\d+$/.test(value)) {
    return null;
  }

  return Number(value);
}

export function taskPortSlotForSlug(slug: string): number {
  return Number.parseInt(createHash("sha1").update(slug).digest("hex").slice(0, 8), 16) % TASK_PORT_SLOT_COUNT;
}

export function taskPortsForSlot(slot: number): TaskPorts {
  const base = TASK_PORT_BASE + slot * TASK_PORT_BLOCK_SIZE;
  return {
    slot,
    apiPort: base,
    dashPort: base + 1,
    sitePort: base + 2,
    adminPort: base + 3,
    storybookPort: base + 4,
    ciApiPort: base + 5,
    ciDashPort: base + 6,
    accountPort: base + 7,
  };
}

export function taskPortsFromEnv(values: Record<string, string>): TaskPorts | null {
  const apiPort = numberFromEnv(values, "API_PORT");
  const dashPort = numberFromEnv(values, "DASH_PORT");
  const sitePort = numberFromEnv(values, "SITE_PORT");
  const adminPort = numberFromEnv(values, "ADMIN_PORT");
  const storybookPort = numberFromEnv(values, "STORYBOOK_PORT");
  const ciApiPort = numberFromEnv(values, "CI_API_PORT");
  const ciDashPort = numberFromEnv(values, "CI_DASH_PORT");
  const accountPort = numberFromEnv(values, "ACCOUNT_PORT");
  const hasAccountPort = values["ACCOUNT_PORT"] !== undefined;

  if (
    apiPort === null ||
    dashPort === null ||
    sitePort === null ||
    adminPort === null ||
    storybookPort === null ||
    ciApiPort === null ||
    ciDashPort === null ||
    (hasAccountPort && accountPort === null)
  ) {
    return null;
  }

  return {
    slot: numberFromEnv(values, "GTASK_SLOT") ?? Math.floor((apiPort - TASK_PORT_BASE) / TASK_PORT_BLOCK_SIZE),
    apiPort,
    dashPort,
    sitePort,
    adminPort,
    storybookPort,
    ciApiPort,
    ciDashPort,
    accountPort: accountPort ?? apiPort + 7,
  };
}

function taskPortValues(ports: TaskPorts): Record<string, string> {
  return {
    GTASK_SLOT: String(ports.slot),
    API_PORT: String(ports.apiPort),
    DASH_PORT: String(ports.dashPort),
    SITE_PORT: String(ports.sitePort),
    ADMIN_PORT: String(ports.adminPort),
    STORYBOOK_PORT: String(ports.storybookPort),
    CI_API_PORT: String(ports.ciApiPort),
    CI_DASH_PORT: String(ports.ciDashPort),
    ACCOUNT_PORT: String(ports.accountPort),
    VITE_API_ENDPOINT: `http://127.0.0.1:${ports.apiPort}`,
    VITE_TURNSTILE_SITEKEY: "not-real",
    VITE_GTM_ID: "not-real",
  };
}

export function renderTaskPorts(slug: string, ports: TaskPorts): string {
  const values = taskPortValues(ports);
  return `# Local ports for Gertrude task ${slug}\n# Generated by gt; safe to delete and regenerate with gt setup-ports.\n${Object.entries(values)
    .map(([key, value]) => `${key}=${dotenvValue(value)}`)
    .join("\n")}\n`;
}

export function taskPortsPath(worktreeDir: string): string {
  return join(worktreeDir, ".gtask-ports");
}

function portNumbers(ports: TaskPorts): number[] {
  return [
    ports.apiPort,
    ports.dashPort,
    ports.sitePort,
    ports.adminPort,
    ports.storybookPort,
    ports.ciApiPort,
    ports.ciDashPort,
    ports.accountPort,
  ];
}

function portInUse(port: number): boolean {
  return run("/bin/sh", ["-c", 'nc -z 127.0.0.1 "$1" >/dev/null 2>&1', "sh", String(port)], {
    allowFailure: true,
  }).status === 0;
}

function existingTaskPortFiles(exceptWorktreeDir: string): string[] {
  if (!existsSync(BASE_DIR)) {
    return [];
  }

  return readdirSync(BASE_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => resolve(BASE_DIR, entry.name))
    .filter((worktreeDir) => worktreeDir !== resolve(exceptWorktreeDir))
    .map(taskPortsPath)
    .filter(existsSync);
}

function usedTaskPortFacts(exceptWorktreeDir: string): { slots: Set<number>; ports: Set<number> } {
  const slots = new Set<number>();
  const ports = new Set<number>();

  for (const file of existingTaskPortFiles(exceptWorktreeDir)) {
    const parsed = taskPortsFromEnv(parseSimpleDotenv(readFileSync(file, "utf8")));
    if (!parsed) {
      continue;
    }

    slots.add(parsed.slot);
    for (const port of portNumbers(parsed)) {
      ports.add(port);
    }
  }

  return { slots, ports };
}

function portsAreAvailable(ports: TaskPorts, usedSlots: Set<number>, usedPorts: Set<number>): boolean {
  if (usedSlots.has(ports.slot)) {
    return false;
  }

  for (const port of portNumbers(ports)) {
    if (usedPorts.has(port) || portInUse(port)) {
      return false;
    }
  }

  return true;
}

export function allocateTaskPorts(slug: string, worktreeDir: string): TaskPorts {
  const existingPath = taskPortsPath(worktreeDir);
  if (existsSync(existingPath)) {
    const existing = taskPortsFromEnv(parseSimpleDotenv(readFileSync(existingPath, "utf8")));
    if (existing) {
      return existing;
    }
  }

  const { slots, ports } = usedTaskPortFacts(worktreeDir);
  const preferredSlot = taskPortSlotForSlug(slug);

  for (let offset = 0; offset < TASK_PORT_SLOT_COUNT; offset++) {
    const candidate = taskPortsForSlot((preferredSlot + offset) % TASK_PORT_SLOT_COUNT);
    if (portsAreAvailable(candidate, slots, ports)) {
      return candidate;
    }
  }

  fail("could not find a free task port block");
}

export function setupTaskPorts(worktreeDir: string, slug: string): TaskPorts {
  const ports = allocateTaskPorts(slug, worktreeDir);
  writeFileSync(taskPortsPath(worktreeDir), renderTaskPorts(slug, ports), "utf8");
  return ports;
}
