import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { BASE_DIR } from "./constants.ts";
import { dotenvValue, parseSimpleDotenv } from "./dotenv.ts";

const TASK_METADATA_FILENAME = ".gtask";
const TASK_METADATA_DIRNAME = "scratch";

export type TaskInfo = {
  title: string;
  branchName: string;
  directoryName: string;
  worktreeDir: string;
};

function shortHash(value: string): string {
  return createHash("sha1").update(value).digest("hex").slice(0, 8);
}

export function taskDirectoryNameForTitle(title: string): string {
  if (!title.includes("/")) {
    return title;
  }

  const stem =
    title
      .replace(/[^A-Za-z0-9._-]+/g, "--")
      .replace(/--+/g, "--")
      .replace(/^[^A-Za-z0-9]+|[^A-Za-z0-9]+$/g, "")
      .slice(0, 54)
      .replace(/[^A-Za-z0-9]+$/g, "") || "task";

  return `${stem}-${shortHash(title)}`;
}

export function taskBranchNameForTitle(title: string): string {
  return taskDirectoryNameForTitle(title);
}

export function taskWorktreeDirForTitle(title: string): string {
  return join(BASE_DIR, taskDirectoryNameForTitle(title));
}

export function taskMetadataPath(worktreeDir: string): string {
  return join(worktreeDir, TASK_METADATA_DIRNAME, TASK_METADATA_FILENAME);
}

function legacyTaskMetadataPath(worktreeDir: string): string {
  return join(worktreeDir, TASK_METADATA_FILENAME);
}

function readTaskMetadata(worktreeDir: string): Record<string, string> {
  const metadataPath = taskMetadataPath(worktreeDir);
  if (existsSync(metadataPath)) {
    return parseSimpleDotenv(readFileSync(metadataPath, "utf8"));
  }

  const legacyPath = legacyTaskMetadataPath(worktreeDir);
  if (existsSync(legacyPath)) {
    const contents = readFileSync(legacyPath, "utf8");
    if (contents.startsWith("# Generated by gt.")) {
      mkdirSync(join(worktreeDir, TASK_METADATA_DIRNAME), { recursive: true });
      writeFileSync(metadataPath, contents, "utf8");
      rmSync(legacyPath, { force: true });
      return parseSimpleDotenv(contents);
    }
  }

  return {};
}

function removeGeneratedLegacyMetadata(worktreeDir: string): void {
  const legacyPath = legacyTaskMetadataPath(worktreeDir);
  if (!existsSync(legacyPath)) {
    return;
  }

  const contents = readFileSync(legacyPath, "utf8");
  if (contents.startsWith("# Generated by gt.")) {
    rmSync(legacyPath, { force: true });
  }
}

export function renderTaskMetadata(info: Pick<TaskInfo, "title" | "branchName" | "directoryName">): string {
  return `# Generated by gt.\nGTASK_TITLE=${dotenvValue(info.title)}\nGTASK_BRANCH=${dotenvValue(info.branchName)}\nGTASK_DIRECTORY=${dotenvValue(info.directoryName)}\n`;
}

export function writeTaskMetadata(worktreeDir: string, title: string): TaskInfo {
  const directoryName = basename(worktreeDir);
  const info: TaskInfo = {
    title,
    branchName: taskBranchNameForTitle(title),
    directoryName,
    worktreeDir,
  };
  mkdirSync(join(worktreeDir, TASK_METADATA_DIRNAME), { recursive: true });
  writeFileSync(taskMetadataPath(worktreeDir), renderTaskMetadata(info), "utf8");
  removeGeneratedLegacyMetadata(worktreeDir);
  return info;
}

export function taskInfoForRoot(worktreeDir: string): TaskInfo {
  const resolvedWorktreeDir = resolve(worktreeDir);
  const directoryName = basename(resolvedWorktreeDir);
  const metadata = readTaskMetadata(resolvedWorktreeDir);
  const title = metadata.GTASK_TITLE || directoryName;

  return {
    title,
    branchName: metadata.GTASK_BRANCH || taskBranchNameForTitle(title),
    directoryName,
    worktreeDir: resolvedWorktreeDir,
  };
}

export function findTaskRootByTitle(title: string): string | null {
  if (!existsSync(BASE_DIR)) {
    return null;
  }

  for (const entry of readdirSync(BASE_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }

    const candidate = resolve(BASE_DIR, entry.name);
    if (taskInfoForRoot(candidate).title === title) {
      return candidate;
    }
  }

  return null;
}
